services:
  - type: web
    name: environment-for-database
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "gunicorn manage:app"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "<your-database-url>" # Replace with the actual database URL
      - key: ADMIN_USERNAME
        value: "<your-admin-username>" # Replace with an example username
      - key: ADMIN_PASSWORD
        value: "<your-admin-password>" # Replace with the actual admin password
    plan: free
